version: '3.5'
services:
  web:
    image: "golang-service-demo"
    container_name: "golang-service-container"
    ports: 
      - "12001:12001"
    networks:
      - postgres
    restart: unless-stopped